title: "sashisashi's blog"
description: "Twitterでは長すぎることを書いてます"
url: "https://sashisashi569.github.io"
baseurl: "/blog"

repository: sashisashi569/blog

author:
  name: "sashisashi569"

lang: ja
timezone: Asia/Tokyo

theme: jekyll-theme-minimal

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

sass:
  sass_dir: _sass
  style: compressed
